language: python

matrix:
    include:
        #- os: linux
          #python: 3.7
          #dist: xenial
          #sudo: true
        #- os: linux
          #python: 3.6
          #dist: trusty
          #sudo: false
        #- os: linux
          #python: 3.5
          #dist: trusty
          #sudo: false
        #- os: linux
          #python: 3.4
          #dist: trusty
          #sudo: false
        #- os: linux
          #python: 2.7
          #dist: trusty
          #sudo: false
        - os: osx
          language: generic

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ibmcom/db2express-c; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --name db2  -p 50000:50000 -e DB2INST1_PASSWORD=password -e LICENSE=accept -d ibmcom/db2express-c db2start; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps -as; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -it db2 useradd -ms /bin/bash auth_user -p auth_pass; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -it db2 su - db2inst1 -c "db2 create db sample"; fi

script:
- cd IBM_DB/ibm_db
- pip install .

